// @flow

import type { CardTile, MonsterTileList, Tile } from '../../type/tile';
import {
  aCardTile, bCardTile, cCardTile, dCardTile, eCardTile, eightCardTile, fCardTile,
  fiveCardTile,
  fourCardTile, mCardTile,
  nineCardTile, oneCardTile, pCardTile,
  sevenCardTile,
  sixCardTile, threeCardTile, twoCardTile, xCardTile,
  zeroCardTile,
} from './stat-tile';
import { bottom, bottomLeft, bottomRight, left, right, top, topLeft, topRight } from './corner-tile';
import {
  Abadon,
  Abomination, Airship, Alexander, Alexandria,
  Antlion, Ark,
  Armstrong,
  Ash, Atomos, Bahamut,
  Behemoth,
  BlazerBeetle, BlueNarciss, Boco,
  Bomb,
  Cactuar, CargoShip,
  CarrionWorm,
  Cerberus,
  Chocobo,
  Crawler, DarkMatter,
  Dragonfly, Elixir, ExcaliburII,
  Fang, FatChocobo,
  FeatherCircle, Fenrir,
  Flan,
  Flare, Frog, Gargant,
  Gargoyle,
  Garuda, Genji,
  GimmeCat,
  Goblin,
  GrandDragon,
  Grimlock,
  Hades,
  Hecteyes,
  HedgehogPie, HildaGarde1, HildaGarde3,
  Holy,
  Ifrit, Invincible,
  Ironite,
  IronMan, Leviathan, Lindblum,
  LizardMan, Madeen,
  Malboro,
  Mandragora, Masamune,
  Meteor,
  Mimic, Mog,
  Mover, MythrilSword, Namingway,
  NovaDragon,
  Nymph,
  Ochu, Odin, Oglop,
  Ogre,
  Ozma,
  Ragtimer,
  Ralvuimago,
  Ramuh, RedRose, Ribbon,
  Sahagin,
  SandGolem,
  SandScorpion, SaveTheQueen,
  Shiva,
  Skeleton,
  Stroper,
  Tantarian, TheaterShip, TigerRacket,
  Tonberry,
  Troll, TwoMoons, UltimaWeapon,
  Vepal,
  Veteran,
  Viltgance,
  Wraith,
  Wyerd,
  Yeti,
  Zaghnol,
  Zemzelett,
  Zombie,
  Zuu,
} from './monster-tile';


export const blueCardTile: Tile = {
  x: 18,
  y: 822,
  width: 42,
  height: 51,
};

export const redCardTile: Tile = {
  x: 66,
  y: 822,
  width: 42,
  height: 51,
};

export const monsterList: MonsterTileList = {
  Goblin,
  Fang,
  Skeleton,
  Flan,
  Zaghnol,
  LizardMan,
  Zombie,
  Bomb,
  Ironite,
  Sahagin,
  Yeti,
  Mimic,
  Wyerd,
  Mandragora,
  Crawler,
  SandScorpion,
  Nymph,
  SandGolem,
  Zuu,
  Dragonfly,
  CarrionWorm,
  Cerberus,
  Antlion,
  Cactuar,
  GimmeCat,
  Ragtimer,
  HedgehogPie,
  Ralvuimago,
  Ochu,
  Troll,
  BlazerBeetle,
  Abomination,
  Zemzelett,
  Stroper,
  Tantarian,
  GrandDragon,
  FeatherCircle,
  Hecteyes,
  Ogre,
  Armstrong,
  Ash,
  Wraith,
  Gargoyle,
  Vepal,
  Grimlock,
  Tonberry,
  Veteran,
  Garuda,
  Malboro,
  Mover,
  Abadon,
  Behemoth,
  IronMan,
  NovaDragon,
  Ozma,
  Hades,
  Holy,
  Meteor,
  Flare,
  Shiva,
  Ifrit,
  Ramuh,
  Atomos,
  Odin,
  Leviathan,
  Bahamut,
  Ark,
  Fenrir,
  Madeen,
  Alexander,
  ExcaliburII,
  UltimaWeapon,
  Masamune,
  Elixir,
  DarkMatter,
  Ribbon,
  TigerRacket,
  SaveTheQueen,
  Genji,
  MythrilSword,
  BlueNarciss,
  HildaGarde3,
  Invincible,
  CargoShip,
  HildaGarde1,
  RedRose,
  TheaterShip,
  Viltgance,
  Chocobo,
  FatChocobo,
  Mog,
  Frog,
  Oglop,
  Alexandria,
  Lindblum,
  TwoMoons,
  Gargant,
  Namingway,
  Boco,
  Airship,
};

export const cardTiles: CardTile = {
  red: redCardTile,
  blue: blueCardTile,
  '0': zeroCardTile,
  '1': oneCardTile,
  '2': twoCardTile,
  '3': threeCardTile,
  '4': fourCardTile,
  '5': fiveCardTile,
  '6': sixCardTile,
  '7': sevenCardTile,
  '8': eightCardTile,
  '9': nineCardTile,
  A: aCardTile,
  B: bCardTile,
  C: cCardTile,
  D: dCardTile,
  E: eCardTile,
  F: fCardTile,
  P: pCardTile,
  M: mCardTile,
  X: xCardTile,
  monster: monsterList,
  corner: {
    topLeft,
    top,
    topRight,
    right,
    bottomRight,
    bottom,
    bottomLeft,
    left,
  },
};
